version: 2.1
orbs:
  node: circleci/node@4.1.0
  codecov: codecov/codecov@1.0.2
workflows:
  node-tests:
    jobs:
      - unit-test

jobs:
  unit-test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: yarn install
      - run: yarn test:coverage
      - codecov/upload:
          file: "./coverage"