name: Generate changelog

on: push
# on:  
#   release:
#     types: # This configuration does not affect the page_build event above
#       - created

jobs:
  generate-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # 👈 Required to retrieve git history
          ref: ${{ github.ref }}
      - name: Install dependencies
        run: yarn
      - name: Generate changelog
        run: yarn gitmoji-changelog
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          message: ':bookmark: generate changelog'
          add: 'CHANGELOG.md'