name: Generate changelog
on: push

jobs:
  run:
    name: Generate changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # 👈 Required to retrieve git history
      - name: "GitHub Version Bumper"
        uses: "kaangokdemir/github-version-bumper@master"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_NAME: "Mark Lyck"
          GITHUB_EMAIL: "mark.lyck@gmail.com"
          VERSION_FILE_NAME: "package.json"
      - name: Install dependencies
        run: yarn
      - name: Generate changelog
        run: yarn gitmoji-changelog
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          message: ':bookmark: generate changelog'
          add: 'CHANGELOG.md'