name: Generate changelog
on: push

jobs:
  run:
    name: Generate changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install dependencies
        run: npm install

      - name: Update source code
        run: yarn generate-changelog

      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          message: ':bookmark: generate changelog'
          add: 'CHANGELOG.md'